"""
Category ORM model.

Table: categories
- UUID primary key (generated by PostgreSQL gen_random_uuid())
- name: unique, max 50 chars
- Relationships: one-to-many with Expense and Budget

Seeded on startup with 9 starter categories if the table is empty
(see app/main.py lifespan hook).
"""
import uuid

from sqlalchemy import String, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin


class Category(Base, TimestampMixin):
    __tablename__ = "categories"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    name: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        unique=True,
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    expenses: Mapped[list["Expense"]] = relationship(  # noqa: F821
        "Expense",
        back_populates="category",
        lazy="select",
    )
    budgets: Mapped[list["Budget"]] = relationship(  # noqa: F821
        "Budget",
        back_populates="category",
        lazy="select",
    )

    def __repr__(self) -> str:
        return f"<Category id={self.id} name={self.name!r}>"
