"""
Category ORM model.

Table: categories
- UUID primary key (generated by PostgreSQL gen_random_uuid())
- name: unique, max 50 chars
- Relationships: one-to-many with Expense and Budget

Seeded on startup with 9 starter categories if the table is empty
(see app/main.py lifespan hook).
"""
import uuid

from sqlalchemy import ForeignKey, Index, String, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin


class Category(Base, TimestampMixin):
    __tablename__ = "categories"

    __table_args__ = (
        Index(
            "uix_categories_name_user",
            "name",
            text("coalesce(user_id, '00000000-0000-0000-0000-000000000000'::uuid)"),
            unique=True,
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    name: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    expenses: Mapped[list["Expense"]] = relationship(  # noqa: F821
        "Expense",
        back_populates="category",
        lazy="select",
    )
    budgets: Mapped[list["Budget"]] = relationship(  # noqa: F821
        "Budget",
        back_populates="category",
        cascade="all, delete-orphan",
        passive_deletes=True,
        lazy="select",
    )
    user: Mapped["User | None"] = relationship(  # noqa: F821
        "User",
        back_populates="custom_categories",
        lazy="select",
    )

    def __repr__(self) -> str:
        return f"<Category id={self.id} name={self.name!r}>"
